### ISSUE TITLE
`async`/`await` support?

### ISSUE THREAD

**Issue by jcurtis** [RyanZim/eslint-config-problems#2]
I love the idea behind this config, but it's complaining about `async` / `await` in my Node 8 code.

**Comment by RyanZim** [comment]
Do you have `ecmaVersion: 8` or higher set under your `parserOptions` in your eslint config?

**Comment by RyanZim** [comment]
I believe project configs would merge with it, with the project config having priority where they conflict.

Adding `ecmaVersion` to the presets would make sense if the Node version supports all new syntax in that `ecmaVersion`.

**Comment by RyanZim** [comment]
Done in v2.0.0 :tada:
