### ISSUE TITLE
Rule: strict

### ISSUE THREAD

**Issue by vimtaai** [RyanZim/eslint-config-problems#3]
Hi,

I see that the rule `strict` is enabled by your config. I find that strange, as writing `"use strict"` in all my source files when writing a module in 2019 is unnecessary, especially that *Module code is always strict mode code.* 

> 10.2.1 Strict Mode Code
> [...]
> 
> * Module code is always strict mode code.
>
> [...]

Shouldn't this rule be opt-in when writing code for the browser instead of opt-out for node.js? I mean, most of the time we use some kind of bundler for browser code which puts the `"use strict"` there anyway.

**Comment by RyanZim** [comment]
If you're writing ES Modules, you should set:
```json
{
  "parserOptions": {
     "sourceType": "module"
  }
}
```
This will modify the behavior of the `strict` rule to disallow the use of `"use strict"`. Actually, ESLint will error out if you use `export` or `import` keywords without this set.

If you're not writing ES Modules, but you're using a browser bundler that auto-inserts `"use strict"`, set: 
```json
{
  "parserOptions": {
    "ecmaFeatures": {
      "impliedStrict": true
    }
  }
}
```

See https://eslint.org/docs/rules/strict#rule-details for details.

---

This does highlight a flaw in the documentation, though. This should be documented. PR welcome.

**Comment by vimtaai** [comment]
Thanks for the response. 😄 
Maybe when Node 12 will become LTS and will support `import`/`export` without a flag we'll have a `node12` subconfig with `strict` being unnecessary.

**Comment by RyanZim** [comment]
Yeah, we'll have to evaluate at some point when modules are enough of the norm to make that the default.
