### ISSUE TITLE
Missing node8 subconfig

### ISSUE THREAD

**Issue by vimtaai** [RyanZim/eslint-config-problems#5]
I installed the new 3.0 version and try to run eslint. It says that it cannot find module `eslint-config-problems/node8` when using the `node10` subconfig. 

The `node10.js` file references the removed `node8` subconfig:

https://github.com/RyanZim/eslint-config-problems/blob/39ecc6a36cbd8132bbdacea950f51d923542c67b/node10.js#L3

 How should I solve this?

**Comment by RyanZim** [comment]
Argh, good catch. The `node8` config was removed because the rules were merged into the default config now that Node 6 is unsupported. I didn't realize that `node10` still referenced `node8`. Will issue a patch.

**Comment by RyanZim** [comment]
Patched in v1.0.1
